// <auto-generated />
using System;
using Linky.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linky.Migrations
{
    [DbContext(typeof(LinkyDbContext))]
    [Migration("20241117235256_Aliases")]
    partial class Aliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Linky.Client.Models.Link", b =>
                {
                    b.Property<uint>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.HasIndex("Url", "Type")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Linky.Client.Models.Link+Alias", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<uint?>("LinkUid")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.HasIndex("LinkUid");

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Linky.Client.Models.Link+Alias", b =>
                {
                    b.HasOne("Linky.Client.Models.Link", null)
                        .WithMany("Aliases")
                        .HasForeignKey("LinkUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linky.Client.Models.Link", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
